[phases.setup]
nixPkgs = ["python39", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && gunicorn -c gunicorn_config.py app:app"
